### PR TITLE
Fix translation for provider validation message

### PR DESCRIPTION
**Pull request by kavyanekkalapu**
This is to fix https://github.ibm.com/IBMPrivateCloud/CP4MCM/issues/8755

Added translation for error message in provider validation

Issue:

### CODE REVIEW

**Comment by agrare** [comment]
> This is to fix https://github.ibm.com/IBMPrivateCloud/CP4MCM/issues/8755

Hey @kavyanekkalapu that isn't a publicly available issue and thus shouldn't be in an upstream pull request

**Comment by agrare** [comment]
@kavyanekkalapu it looks like the image you tried to upload didn't make it

**Review by agrare — APPROVED** [review]

**Comment by agrare** [comment]
@kavyanekkalapu please update the description

**Comment by kavyanekkalapu** [comment]
> @kavyanekkalapu it looks like the image you tried to upload didn't make it

thanks for pointing out, fixed image and removed issue link.

**Pull request merged**
